### ISSUE TITLE
Refactor the AsyncCallable method to use Java lambdas

### ISSUE THREAD

**Issue by animo93** [animo93/JRest#36]
The `AsyncCallable` class along with few other methods can be redesigned to use Java 8 lambda expressions like Supplier , Function , Predicate and Consumer .
Also need to add test cases for the asynchronous calls which are missing

**Comment by 3looy-hubs** [comment]
Can you assign me

**Comment by animo93** [comment]
Hi @3looy-hubs , 
I have assigned you this issue . 
Please feel free to fork this repo and create a PR

**Comment by animo93** [comment]
Merged PR
