### ISSUE TITLE
Enhancement for adding query parameters

### ISSUE THREAD

**Issue by animo93** [animo93/JRest#5]
Currently Query can be set globally while building the API only . Need to enable query parameter in the API method  as a parameter . It should be along the below lines 
`Call<List<User>> groupList(@Path("id") int groupId, @Query("sort") String sort);`
and 
`Call<List<User>> groupList(@Path("id") int groupId, @QueryMap Map<String, String> options);`

**Comment by federicocosentino87** [comment]
Hi, can i take this issue?

I already analysed the enhancement, for the single query parameter there is no problem, but for the map it is not possible.

The @interface annotation allow as parameters only primitives or array of primitives, so there is no way to pass a Map through annotation.

**Comment by animo93** [comment]
Hi @federicocosentino87 ,

Please feel free to take up this issue .
I have already started working on this issue on a separate branch "query-params" . You can make you changes and submit a PR on it .

**Comment by HarshitRaj** [comment]
hey @animo93 ,
I forked and worked on this and was able to add both types of query param from the above enhancement list i.e 'Query' and 'QueryMap'. :)
Additionaly, I also added compatibility for 'http' calls as well. Till now, the code only supported 'https'.

Let me know if we are still working on this and I can create a PR for your review.

**Comment by animo93** [comment]
Hi @HarshitRaj ,

Thanks for the help . 
Please feel free to submit a PR for review

**Comment by HarshitRaj** [comment]
@animo93 
created PR :)

**Comment by animo93** [comment]
Merged .
Thanks for the PR :)
