### ISSUE TITLE
Optimizing and Cleaning up existing repo

### ISSUE THREAD

**Issue by JacobSherrod** [animo93/JRest#9]
I would like to make a few formatting suggestions if you are open to them.

**Comment by JacobSherrod** [comment]
I have the changes available if you would like me to open up a branch

**Comment by animo93** [comment]
Hi @JacobSherrod , 
I am open to formatting suggestions .
Please feel free to submit PR

**Comment by JacobSherrod** [comment]
https://github.com/animo93/JRest/pull/10

**Comment by animo93** [comment]
Merged PR
